version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: ipdb
    versions:
    - 0.13.4
    - 0.13.5
    - 0.13.6
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: pytest-django
    versions:
    - 4.1.0
  - dependency-name: pillow
    versions:
    - 6.2.0
